import React from 'react'

export const Home = () => (
    <div>
      <h2>Hello World</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, vero. Dolore impedit pariatur labore cumque obcaecati asperiores soluta, tenetur repellendus cum, voluptatibus totam. Amet nemo dolores sit deleniti placeat modi autem beatae non voluptas officiis, accusamus unde quo nostrum ducimus consequuntur eius ex tempora minima esse a aliquam incidunt reiciendis recusandae possimus. Quibusdam sequi nemo libero dignissimos ea quo laudantium expedita iusto sapiente voluptate beatae reprehenderit impedit itaque illo similique accusamus, illum deserunt at perspiciatis eos maxime dolorum! Possimus, cum consectetur praesentium magnam numquam recusandae veniam illo nesciunt fuga. Possimus delectus totam, magni dolorum amet sint distinctio adipisci blanditiis aspernatur?</p>
      <p>Fusce porta erat at enim pellentesque posuere. Donec non arcu rhoncus, faucibus nulla sit amet, porta tortor. Suspendisse dictum nisi neque, sed luctus quam efficitur quis. Mauris suscipit erat non dui euismod placerat. In gravida vestibulum felis, a gravida tortor finibus nec. Nulla facilisi. Maecenas sed ex ac erat rhoncus pellentesque vitae id quam. Etiam blandit, nisl eget efficitur finibus, tellus ex volutpat dui, nec pretium justo justo at nisl. Cras augue est, auctor pellentesque velit non, dapibus egestas leo. Aliquam sed arcu nibh. Quisque diam ligula, ullamcorper nec luctus ut, lacinia quis lectus. Quisque non interdum augue, porttitor imperdiet nunc. Sed consectetur vel mauris in mollis. Fusce a vestibulum nunc, vel efficitur sapien. Integer aliquam ex tincidunt, malesuada tortor ut, euismod erat.</p>
      <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse vestibulum tellus lectus, in posuere dolor vestibulum eget. Ut mauris quam, ullamcorper vel diam sed, finibus aliquam felis. Nam euismod massa eu sapien hendrerit tempus. Mauris fringilla interdum lorem pharetra congue. Nullam lorem est, faucibus in suscipit in, suscipit vitae diam. Nullam varius, leo sit amet posuere posuere, purus tortor porta nunc, in eleifend augue tortor luctus nibh. Maecenas eget elementum sem. Mauris at orci tristique purus dignissim imperdiet ac et mauris. Fusce id tellus fringilla velit vulputate iaculis. Nam faucibus tellus lorem, ut posuere est tincidunt nec.</p>
    </div>
  )
